obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.3
inflation_radius: 0.1

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: LiDar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

